import { gql } from "graphql-tag";

/**
 * Unified frame-scoped analysis (ADR-0007). One bitemporal `analysis` row
 * per (frame × schemaVersion), generated by the pipeline over an arbitrary
 * FRAME expressed as the same dimensions the knowledgebase is indexed on
 * (locationIds / eventTypes / needSectors / window). Generalises
 * `SituationAnalysis` (country-default frame) and subsumes `Crisis`
 * ("crisis overview" = an event-derived frame).
 *
 * The `data` payload is deliberately opaque `JSON!`, versioned by
 * `schemaVersion` — the situation taxonomy plus a `scenarios` component; see
 * the Pydantic schemas in clear-pipeline for the exact shape.
 */
export const analysisTypeDef = gql`
  """A single frame-scoped analysis snapshot. Cache read path — always the
  current row for its frame unless \`asOf\` is supplied for a historical read."""
  type Analysis {
    id: String!

    """── Frame ── The dimensions this analysis was generated over, the same
    ones the knowledgebase is filtered by. Arrays are canonicalised (sorted +
    de-duplicated) on write so frame identity is stable."""
    locationIds: [String!]!
    eventTypes: [String!]!
    needSectors: [String!]!

    windowStart: DateTime!
    """Window end. \`null\` means rolling "to present" (an automated
    analysis); a value means a fixed range (on-demand). The concrete "as of"
    instant of a rolling row is \`generatedAt\` / \`validFrom\`."""
    windowEnd: DateTime

    """Full analysis blob (situation taxonomy + \`scenarios\`). Opaque and
    versioned by \`schemaVersion\`; LLM components carry their own
    \`source_report_ids\` for per-component provenance."""
    data: JSON!

    """Denormalised union of every contributing report id across components.
    Per-field datapoint provenance lives inside \`data\` — a frame can span
    many aggregated-datapoints rows, so there is no single bucket reference."""
    sourceReportIds: [String!]!

    generatedByModel: String!
    generationCostUsd: Float
    generatedAt: DateTime!

    """Last time any trigger checked this frame (manual sync or automation),
    whether or not it regenerated (ADR-0008). On a gate skip (within the 24h
    floor, or no new evidence) this advances while \`generatedAt\` does not."""
    lastSyncedAt: DateTime

    """Bitemporal validity — \`validTo\` is null while this is the current row
    for its frame, else the timestamp a regeneration superseded it."""
    validFrom: DateTime!
    validTo: DateTime

    """Bumped when the payload taxonomy or prompt set changes. Versions
    coexist per frame; trend reads never mix them."""
    schemaVersion: String!
  }

  """A frame — the scope of an analysis. \`windowEnd\` omitted / null means
  rolling "to present". Array members are order-insensitive (canonicalised
  server-side)."""
  input AnalysisFrameInput {
    locationIds: [String!]
    eventTypes: [String!]
    needSectors: [String!]
    windowStart: DateTime!
    windowEnd: DateTime
  }

  input UpsertAnalysisInput {
    """The frame this analysis covers."""
    locationIds: [String!]
    eventTypes: [String!]
    needSectors: [String!]
    windowStart: DateTime!
    windowEnd: DateTime
    data: JSON!
    sourceReportIds: [String!]!
    generatedByModel: String!
    generationCostUsd: Float
    schemaVersion: String!
    """Bypass the 24h regeneration floor (ADR-0008). The pipeline sets this for
    an admin-forced request. Omitted/false: a write within 24h of the current
    row's \`generatedAt\` is a no-op that only bumps \`lastSyncedAt\`."""
    force: Boolean
  }

  """Summary of an \`upsertAnalysis\` mutation — whether it superseded a previous
  row, or was skipped by the 24h regeneration floor (ADR-0008)."""
  type UpsertAnalysisResult {
    """The current analysis row for the frame after the call — the newly-created
    row, or (on a skip) the existing current row."""
    analysisId: String!
    """\`true\` when the mutation stamped \`validTo\` on a previous current row
    for the same frame, \`false\` when this was the first row or a skip."""
    supersededPrevious: Boolean!
    """\`true\` when the 24h floor made this a no-op (only \`lastSyncedAt\` was
    bumped, no new version written). \`false\` on an actual (re)generation."""
    skipped: Boolean!
    """Why the write was skipped (e.g. \`within-24h-floor\`), else null."""
    reason: String
  }

  """Latest-evidence watermark for a frame (ADR-0008), over the \`knowledgebase\`
  retrieval corpus the analysis is generated from. The drain compares
  \`latestEvidenceAt\` to the live analysis's \`generatedAt\` to decide whether
  anything new warrants a regeneration."""
  type FrameEvidenceWatermark {
    """Max ingestion time (\`created_at\`) across knowledgebase rows matching the
    frame, or null when the frame has no evidence yet."""
    latestEvidenceAt: DateTime
    """Count of knowledgebase rows matching the frame."""
    evidenceCount: Int!
  }

  """A subscription that keeps one frame's analysis current on a cadence
  (ADR-0007 §5). The analysis row is shared; the scheduler regenerates each
  frame at the minimum cadence across its subscribers. Automations are always
  rolling ("to present"), so they carry no \`windowEnd\`."""
  type AnalysisAutomation {
    id: String!
    locationIds: [String!]!
    eventTypes: [String!]!
    needSectors: [String!]!
    windowStart: DateTime!
    cadence: String!
    teamId: String
    createdByUserId: String
    enabled: Boolean!
    lastRunAt: DateTime
    nextRunAt: DateTime
    createdAt: DateTime!
    updatedAt: DateTime!
  }

  input CreateAnalysisAutomationInput {
    locationIds: [String!]
    eventTypes: [String!]
    needSectors: [String!]
    windowStart: DateTime!
    """Refresh cadence label, e.g. \`daily\` / \`weekly\`."""
    cadence: String!
    """Owning team. Omit for a system-owned automation (admin only)."""
    teamId: String
  }

  input UpdateAnalysisAutomationInput {
    cadence: String
    enabled: Boolean
  }

  enum AnalysisRequestStatus {
    PENDING
    GENERATED
    FAILED
  }

  """An on-demand analysis generation request (ADR-0007 §4). A user enqueues a
  frame that may not exist yet; a pipeline sensor drains \`pendingAnalyses\`,
  generates + upserts the analysis, and marks the request \`GENERATED\`. Scheduled
  refreshes use \`AnalysisAutomation\` instead of this one-shot queue."""
  type AnalysisRequest {
    id: String!
    locationIds: [String!]!
    eventTypes: [String!]!
    needSectors: [String!]!
    windowStart: DateTime!
    windowEnd: DateTime
    status: AnalysisRequestStatus!
    requestedByUserId: String
    teamId: String
    """Admin force (ADR-0008): the drain bypasses the 24h floor + freshness
    check for this request."""
    force: Boolean!
    attempts: Int!
    lastError: String
    createdAt: DateTime!
    updatedAt: DateTime!
  }

  input RequestAnalysisInput {
    locationIds: [String!]
    eventTypes: [String!]
    needSectors: [String!]
    windowStart: DateTime!
    windowEnd: DateTime
    """Owning team, for a team-scoped on-demand request."""
    teamId: String
    """Force a regeneration past the 24h floor + freshness gate (ADR-0008).
    Admin only — a non-admin passing \`true\` is rejected."""
    force: Boolean
  }
`;
