import { gql } from "graphql-tag";

/**
 * Unified frame-scoped analysis (ADR-0007). One bitemporal `analysis` row
 * per (frame × schemaVersion), generated by the pipeline over an arbitrary
 * FRAME expressed as the same dimensions the knowledgebase is indexed on
 * (locationIds / eventTypes / needSectors / window). Generalises
 * `SituationAnalysis` (country-default frame) and subsumes `Crisis`
 * ("crisis overview" = an event-derived frame).
 *
 * The `data` payload is deliberately opaque `JSON!`, versioned by
 * `schemaVersion` — the situation taxonomy plus a `scenarios` component; see
 * the Pydantic schemas in clear-pipeline for the exact shape.
 */
export const analysisTypeDef = gql`
  """A single frame-scoped analysis snapshot. Cache read path — always the
  current row for its frame unless \`asOf\` is supplied for a historical read."""
  type Analysis {
    id: String!

    """── Frame ── The dimensions this analysis was generated over, the same
    ones the knowledgebase is filtered by. Arrays are canonicalised (sorted +
    de-duplicated) on write so frame identity is stable."""
    locationIds: [String!]!
    eventTypes: [String!]!
    needSectors: [String!]!

    windowStart: DateTime!
    """Window end. \`null\` means rolling "to present" (an automated
    analysis); a value means a fixed range (on-demand). The concrete "as of"
    instant of a rolling row is \`generatedAt\` / \`validFrom\`."""
    windowEnd: DateTime

    """Full analysis blob (situation taxonomy + \`scenarios\`). Opaque and
    versioned by \`schemaVersion\`; LLM components carry their own
    \`source_report_ids\` for per-component provenance."""
    data: JSON!

    """Denormalised union of every contributing report id across components.
    Per-field datapoint provenance lives inside \`data\` — a frame can span
    many aggregated-datapoints rows, so there is no single bucket reference."""
    sourceReportIds: [String!]!

    generatedByModel: String!
    generationCostUsd: Float
    generatedAt: DateTime!

    """Bitemporal validity — \`validTo\` is null while this is the current row
    for its frame, else the timestamp a regeneration superseded it."""
    validFrom: DateTime!
    validTo: DateTime

    """Bumped when the payload taxonomy or prompt set changes. Versions
    coexist per frame; trend reads never mix them."""
    schemaVersion: String!
  }

  """A frame — the scope of an analysis. \`windowEnd\` omitted / null means
  rolling "to present". Array members are order-insensitive (canonicalised
  server-side)."""
  input AnalysisFrameInput {
    locationIds: [String!]
    eventTypes: [String!]
    needSectors: [String!]
    windowStart: DateTime!
    windowEnd: DateTime
  }

  input UpsertAnalysisInput {
    """The frame this analysis covers."""
    locationIds: [String!]
    eventTypes: [String!]
    needSectors: [String!]
    windowStart: DateTime!
    windowEnd: DateTime
    data: JSON!
    sourceReportIds: [String!]!
    generatedByModel: String!
    generationCostUsd: Float
    schemaVersion: String!
  }

  """Summary of an \`upsertAnalysis\` mutation — reports whether the write
  superseded a previously-current row for the same frame."""
  type UpsertAnalysisResult {
    analysisId: String!
    """\`true\` when the mutation stamped \`validTo\` on a previous current row
    for the same frame, \`false\` when this was the first row for the frame."""
    supersededPrevious: Boolean!
  }

  """A subscription that keeps one frame's analysis current on a cadence
  (ADR-0007 §5). The analysis row is shared; the scheduler regenerates each
  frame at the minimum cadence across its subscribers. Automations are always
  rolling ("to present"), so they carry no \`windowEnd\`."""
  type AnalysisAutomation {
    id: String!
    locationIds: [String!]!
    eventTypes: [String!]!
    needSectors: [String!]!
    windowStart: DateTime!
    cadence: String!
    teamId: String
    createdByUserId: String
    enabled: Boolean!
    lastRunAt: DateTime
    nextRunAt: DateTime
    createdAt: DateTime!
    updatedAt: DateTime!
  }

  input CreateAnalysisAutomationInput {
    locationIds: [String!]
    eventTypes: [String!]
    needSectors: [String!]
    windowStart: DateTime!
    """Refresh cadence label, e.g. \`daily\` / \`weekly\`."""
    cadence: String!
    """Owning team. Omit for a system-owned automation (admin only)."""
    teamId: String
  }

  input UpdateAnalysisAutomationInput {
    cadence: String
    enabled: Boolean
  }

  enum AnalysisRequestStatus {
    PENDING
    GENERATED
    FAILED
  }

  """An on-demand analysis generation request (ADR-0007 §4). A user enqueues a
  frame that may not exist yet; a pipeline sensor drains \`pendingAnalyses\`,
  generates + upserts the analysis, and marks the request \`GENERATED\`. Scheduled
  refreshes use \`AnalysisAutomation\` instead of this one-shot queue."""
  type AnalysisRequest {
    id: String!
    locationIds: [String!]!
    eventTypes: [String!]!
    needSectors: [String!]!
    windowStart: DateTime!
    windowEnd: DateTime
    status: AnalysisRequestStatus!
    requestedByUserId: String
    teamId: String
    attempts: Int!
    lastError: String
    createdAt: DateTime!
    updatedAt: DateTime!
  }

  input RequestAnalysisInput {
    locationIds: [String!]
    eventTypes: [String!]
    needSectors: [String!]
    windowStart: DateTime!
    windowEnd: DateTime
    """Owning team, for a team-scoped on-demand request."""
    teamId: String
  }
`;
