import { gql } from "graphql-tag";

export const crisisTypeDef = gql`
  """A crisis aggregates multiple events into a single coherent narrative."""
  type Crisis {
    id: String!
    title: String
    summary: String
    """Forward-looking scenarios generated by the LLM enrichment task.
    Shape: { most_likely, best_case, worst_case, description }. Null until
    the enrichment task runs."""
    scenarios: JSON
    """Severity score (aggregated from linked events)."""
    severity: Float!
    """General location of the crisis."""
    generalLocation: Location
    """Needs associated with the crisis (JSON structure)."""
    needs: JSON!
    """Population directly affected by linked events (BigInt as string)."""
    populationAffected: String
    """Total population residing within the admin areas of linked events (BigInt as string)."""
    populationInArea: String
    """Supporting documents uploaded by users (reports, photos, PDFs).
    Returned as presigned URLs — the underlying storage is S3 keys, which
    the resolver converts at read time so links stay short-lived."""
    attachments: [String!]!
    """Events that are part of this crisis."""
    events: [Event!]!
    """User feedback on this crisis."""
    feedbacks: [UserFeedback!]!
    """User comments on this crisis."""
    comments: [UserComment!]!
  }

  """Link between a crisis and an event."""
  type EventCrisis {
    id: String!
    crisisId: String!
    eventId: String!
    collectedAt: DateTime!
    crisis: Crisis!
    event: Event!
  }

  input CreateCrisisFromEventsInput {
    title: String
    summary: String
    severity: Float!
    locationId: String
    """Needs as JSON."""
    needs: JSON!
    """Event IDs to link to the newly created crisis (must not be empty)."""
    eventIds: [String!]!
  }
`;
